-- STUDENT TABLES --

USE PLACEMENT_MANAGEMENT;
CREATE TABLE STUDENT(
		STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
		fullName VARCHAR(20) NOT NULL,
		dob VARCHAR(10) NOT NULL,
		email VARCHAR(50) NOT NULL,
		password VARCHAR(10) NOT NULL,
		phone VARCHAR(15) NOT NULL,
        photo BLOB NOT NULL,
        resume BLOB NOT NULL
);

CREATE TABLE ACCADEMIC_DETAILS(
        ACCADEMIC_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
		STUDENT_ID INT,
		collegeName VARCHAR(20) NOT NULL,
        department VARCHAR(10) NOT NULL,
        dgpa DECIMAL(3,2) NOT NULL,
		FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
);

CREATE TABLE STUDENT_SKILLS(
        STUDENT_SKILLS_ID INT AUTO_INCREMENT PRIMARY KEY,
		STUDENT_ID INT,
        languages TEXT,
		skills JSON NOT NULL,
		FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
);

CREATE TABLE APPLICATION(
		STUDENT_ID INT,
		APPLICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
        companyName VARCHAR(30) NOT NULL,
		jobTitle VARCHAR(30) NOT NULL,
		department VARCHAR(20) NOT NULL,
		employmentType VARCHAR(10) NOT NULL,
		LocationType VARCHAR(10) NOT NULL,
        Location VARCHAR(20) NOT NULL,
		salary VARCHAR(20) NOT NULL,
        submitted TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID)
);

select * from STUDENT;
select * from ACCADEMIC_DETAILS;
select * from APPLICATION;
select * from mock_interview_questions;
select * from STUDENT_SKILLS;