CREATE DATABASE IF NOT EXISTS PLACEMENT_MANAGEMENT;


-- COMPANY TABLES --

USE PLACEMENT_MANAGEMENT;
CREATE TABLE BASIC_DETAILS(
		COMPANY_ID INT AUTO_INCREMENT PRIMARY KEY,
		companyName VARCHAR(50) NOT NULL,
        industry VARCHAR(20) NOT NULL,
		companyType VARCHAR(20) NOT NULL,
		companyCode VARCHAR(20) UNIQUE,
		password VARCHAR(10) NOT NULL,
        STATUS VARCHAR(10) DEFAULT 'PENDING'
);

CREATE TABLE COMPANY_CONTACT_DETAILS(
        COMPANY_CONTACT_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
        COMPANY_ID INT,
		companyPhone VARCHAR(15) NOT NULL,
		companyEmail VARCHAR(50) UNIQUE NOT NULL,
		companyWebsite VARCHAR(100) NOT NULL,
        companyLinkedin VARCHAR(100),
        FOREIGN KEY (COMPANY_ID) REFERENCES BASIC_DETAILS (COMPANY_ID)
);

CREATE TABLE COMPANY_ADDRESS_DETAILS(
        COMPANY_ADDRESS_DETAILS_ID INT AUTO_INCREMENT PRIMARY KEY,
		COMPANY_ID INT,
		companyAddress VARCHAR(200) NOT NULL,
		city VARCHAR(20) NOT NULL,
		state VARCHAR(20) NOT NULL,
		country VARCHAR(20) NOT NULL,
		pincode VARCHAR(15) NOT NULL,
        FOREIGN KEY (COMPANY_ID) REFERENCES BASIC_DETAILS (COMPANY_ID)
);

CREATE TABLE COMPANY_LEGAL_INFO(
        COMPANY_LEGAL_INFO_ID INT AUTO_INCREMENT PRIMARY KEY,
		COMPANY_ID INT,
        cin VARCHAR(30) NOT NULL,
		registrationNum VARCHAR(20) NOT NULL,
		licenseNum VARCHAR(20) NOT NULL,
        gstNum VARCHAR(20) NOT NULL,
		FOREIGN KEY (COMPANY_ID) REFERENCES BASIC_DETAILS (COMPANY_ID)
);

CREATE TABLE JOB_DETAILS(
		COMPANY_ID INT,
		JOB_ID INT AUTO_INCREMENT PRIMARY KEY,
        companyName VARCHAR(30) NOT NULL,
		jobTitle VARCHAR(30) NOT NULL,
		department VARCHAR(20) NOT NULL,
		employmentType VARCHAR(10) NOT NULL,
		LocationType VARCHAR(10) NOT NULL,
        Location VARCHAR(20) NOT NULL,
		salary VARCHAR(20) NOT NULL,
        applicationDeadline VARCHAR(10) NOT NULL,
		jobDescription TEXT NOT NULL,
		FOREIGN KEY (COMPANY_ID) REFERENCES BASIC_DETAILS (COMPANY_ID)
);

CREATE TABLE INTERVIEW(
		COMPANY_ID INT,
		INTERVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
		INTERVIEW_TITLE VARCHAR(50),
		COMPANY_NAME VARCHAR(50),
		STUDENT_NAME VARCHAR(20),
		INTERVIEW_DATE DATE,
		INTERVIEW_TIME TIME,
		INTERVIEWER_NAME VARCHAR(20),
		MEETING_LINK VARCHAR(70),
		FOREIGN KEY (COMPANY_ID) REFERENCES BASIC_DETAILS (COMPANY_ID)
);

select * from BASIC_DETAILS;
select * from INTERVIEW;
select * from COMPANY_CONTACT_DETAILS;
select * from JOB_DETAILS;

-- ADMIN TABLES --

CREATE TABLE ADMIN_PROFILE(
		ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
		adminName VARCHAR(20) NOT NULL,
		userName VARCHAR(20) NOT NULL,
		email VARCHAR(50) NOT NULL,
		password VARCHAR(10) NOT NULL,
		phone VARCHAR(15) NOT NULL
);


SELECT * FROM ADMIN_PROFILE;